### PR TITLE
Add android support.

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Comment by MarijnS95** [comment]
https://crates.io/crates/app_dirs2 already has support for this :slightly_smiling_face:

**Comment by dvc94ch** [comment]
so many different crates doing the same thing. kind of annoying

**Comment by dvc94ch** [comment]
bors pr_status

**Comment by dvc94ch** [comment]
so is this happening?

**Comment by MarijnS95** [comment]
Or switch to `app_dirs2` and officially deprecate this? It makes no sense to have 3 crates doing the same thing...

**Pull request closed without merging**
